### ISSUE TITLE
Zathura document reader?

### ISSUE THREAD

**Issue by salastro** [knassar702/awesome-linux-minimalism#3]
Hello,

I think `zathura` is a good minimal and customizable document viewer. I wonder why it is not on this list.

Thanks for the time.

**Comment by MindPatch** [comment]
hi @salahdin-ahmed  , I added zathura the first commit, but I deleted it again because I found out that it is not completely minimal because it uses `GTK3`, unlike the `GNU GV`  that uses `GTK2`, I will add it again because the `GNU GV` is not customizable like zathura

best regards :heart: :+1: 
@knassar702
